version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP 프로토콜 포트
      - "15672:15672" # 관리 UI 포트
      - "61613:61613" # STOMP 프로토콜 포트
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped
    networks:
      - analyzer-network
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_management rabbitmq_stomp
      && rabbitmq-server"


networks:
  analyzer-network:
    driver: bridge

volumes:
  rabbitmq_data:
  rabbitmq_log: