spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  rabbitmq:
    host: localhost   # Docker Compose host name
    port: 5672        # AMQP port
    username: guest
    password: guest
    virtual-host: /

    template:
      exchange: analyzer.exchange # default Exchane

    listener:
      direct:
        prefetch: 1