spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

    template:
      exchange: analyzer.exchange

    listener:
      direct:
        prefetch: 1

  thymeleaf:
    cache: false

  web:
    resources:
      static-locations: classpath:/static/